PRINT '========================================';
PRINT 'Starting: Creating database "videohostingDB"';
PRINT '========================================';
GO

USE [master];
GO

-- Создаем БД, если её нет
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'videohostingDB')
BEGIN
    CREATE DATABASE [videohostingDB]
    CONTAINMENT = NONE
    ON PRIMARY 
    ( NAME = N'videohostingDB', FILENAME = N'/var/opt/mssql/data/videohostingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
    LOG ON 
    ( NAME = N'videohostingDB_log', FILENAME = N'/var/opt/mssql/data/videohostingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
    WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF;
    PRINT 'Database "videohostingDB" created successfully';
END
ELSE
    PRINT 'Database "videohostingDB" already exists';
GO

-- Настройки БД
PRINT 'Configuring database settings...';
ALTER DATABASE [videohostingDB] SET COMPATIBILITY_LEVEL = 170;
ALTER DATABASE [videohostingDB] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [videohostingDB] SET ANSI_NULLS OFF;
ALTER DATABASE [videohostingDB] SET ANSI_PADDING OFF;
ALTER DATABASE [videohostingDB] SET ANSI_WARNINGS OFF;
ALTER DATABASE [videohostingDB] SET ARITHABORT OFF;
ALTER DATABASE [videohostingDB] SET AUTO_CLOSE OFF;
ALTER DATABASE [videohostingDB] SET AUTO_SHRINK OFF;
ALTER DATABASE [videohostingDB] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [videohostingDB] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [videohostingDB] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [videohostingDB] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [videohostingDB] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [videohostingDB] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [videohostingDB] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [videohostingDB] SET ENABLE_BROKER;
ALTER DATABASE [videohostingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [videohostingDB] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [videohostingDB] SET TRUSTWORTHY OFF;
ALTER DATABASE [videohostingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [videohostingDB] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [videohostingDB] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [videohostingDB] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [videohostingDB] SET RECOVERY FULL;
ALTER DATABASE [videohostingDB] SET MULTI_USER;
ALTER DATABASE [videohostingDB] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [videohostingDB] SET DB_CHAINING OFF;
ALTER DATABASE [videohostingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF );
ALTER DATABASE [videohostingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [videohostingDB] SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE [videohostingDB] SET ACCELERATED_DATABASE_RECOVERY = OFF;
ALTER DATABASE [videohostingDB] SET OPTIMIZED_LOCKING = OFF;
ALTER DATABASE [videohostingDB] SET QUERY_STORE = ON;
ALTER DATABASE [videohostingDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON);
PRINT 'Database settings configured';
GO

PRINT '========================================';
PRINT 'Database creation completed';
PRINT '========================================';
GO